t = int(input("insira um numero = "))

print("sua tabuada do =",t,"do Numero 1 ate o 10")
print()
print(t,"x 1 =",t * 1)
print()
print(t,"x 2 =",t * 2)
print()
print(t,"x 3 =",t * 3)
print()
print(t,"x 4 =",t * 4)
print()
print(t,"x 5 =",t * 5)
print()
print(t,"x 6 =",t * 6)
print()
print(t,"x 7 =",t * 7)
print()
print(t,"x 8 =",t * 8)
print()
print(t,"x 9 =",t * 9)
print()
print(t,"x 10 =",t * 10)

print()

print("a tabuada sera do numero 11 ate o numero 20 aperte qualquer tecla para prosseguir")
print(t,"x 12 =",t * 11)
print(t,"x 12 =",t * 12)
print(t,"x 13 =",t * 13)
print(t,"x 14 =",t * 14)
print(t,"x 15 =",t * 15)
print(t,"x 16 =",t * 16)
print(t,"x 17 =",t * 17)
print(t,"x 18 =",t * 18)
print(t,"x 19 =",t * 19)
print(t,"x 20 =",t * 20)
